### ISSUE TITLE
Multi gpu

### ISSUE THREAD

**Issue by bhralz** [rixez/Brats21_KAIST_MRI_Lab#3]
Could you please describe multi gpu running of this code?
if possible please leave sample code!
thanks

**Comment by rixez** [comment]
Hi @bhralzz,
Currently, I can't test multi gpu training since my setup only has 1 GPU.
Please check the original nnUNet model for instructions regarding multi-GPU training ([link](https://github.com/MIC-DKFZ/nnUNet#multi-gpu-training))
You might need to modify the Generic_UNet and trainer class to accommodate multi-gpu training.
I hope this helps.
