### ISSUE TITLE
The number of patch

### ISSUE THREAD

**Issue by wxr521314** [rixez/Brats21_KAIST_MRI_Lab#4]
Hi friends，
       Here I go again. I have some questions for you, My data is in 3D. I want to know how many patches my data is divided into. My patch_size is 24x320x320. Can I understand that 24 represents the number of data layers? However, some of my data is less than 24 layers. How did he input it to the network?
Best wish!

**Comment by rixez** [comment]
Hi @wxr521314,
Seems like 24 represents the number of slices in the 3D volume. If this patch size is the result from nnUNet's preprocessing and planning step, I don't think you have anything to worry about. Since the network is fully convolutional, it should be possible to use input with different patch size, granted that the downsampling and upsampling operations result in the same dimension. For data with less than 24 slices, I think you can zero pad before doing inference or training.

**Comment by wxr521314** [comment]
Ok, I see. Thank you very much.
In addition, how many patches is a data divided into? How do we look at this? Or where to watch it?

**Comment by rixez** [comment]
During training, a batch of 3D volumes is selected and one random patch per volume will be extracted for training. 
You can check the class below for more info about data loading
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/d652f9ad3065d1a477b7417c3fc0453f64564a0d/nnunet/training/dataloading/dataset_loading.py#L155
