### ISSUE TITLE
Training my own dataset with axial attention network

### ISSUE THREAD

**Issue by ysl2** [rixez/Brats21_KAIST_MRI_Lab#9]
I would like to know which parameters in the axial attention network are to be modified if for custom datasets? Since your dataset is (128, 128, 128) and my own dataset is (24, 64, 80), I don't know which parts of the network need to be modified in order to satisfy this condition. Thanks!

**Comment by ysl2** [comment]
![image](https://user-images.githubusercontent.com/39717545/167148067-65d68cd3-5c4f-454a-b311-efedcd01a527.png)

**Comment by ysl2** [comment]
![image](https://user-images.githubusercontent.com/39717545/167148237-7f5b36f9-c768-4172-abed-ba4976b8840c.png)

**Comment by rixez** [comment]
Hi @ysl2,
Sorry for the problem. Seems like you already checked the other issue regarding the shape problem and none of the options there work for you. Since your dataset is quite different from the Brats dataset, which leads to different preprocessing and network architecture, I recommend  manually checking the shape for the axial attention embedding! You can modify the shape to the axial embedding in this part:
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/6dfd1a4cb66be5ec94b9b7c102b0e5e89d8ec657/nnunet/network_architecture/generic_UNet.py#L642
